# Generated by Django 4.2.3 on 2025-05-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ad',
            name='title',
        ),
        migrations.AddField(
            model_name='ad',
            name='cities',
            field=models.ManyToManyField(related_name='ads', to='ads.city'),
        ),
    ]
