# Generated by Django 4.2.3 on 2025-06-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ad_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='moderator_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
