# Generated by Django 4.2.3 on 2025-10-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_city_moderator_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_confident',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='appstore_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='playmarket_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='required_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='text_for_share',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='text_for_upload',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='update_text',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
