# Generated by Django 4.2.23 on 2025-10-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_city_text_for_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='text_for_upload',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
