# Generated by Django 4.2.23 on 2025-10-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_city_text_for_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='appstore_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='playmarket_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='update_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='update_text',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
