# Generated by Django 4.2.23 on 2025-10-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_city_appstore_link_city_playmarket_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='update_available',
        ),
        migrations.AddField(
            model_name='city',
            name='required_version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
