# Generated by Django 4.2.23 on 2025-10-24 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_ad_is_confident_city_appstore_link_and_more'),
        ('ads', '0009_remove_city_update_available_city_required_version'),
    ]

    operations = [
    ]
