# Generated by Django 4.2.3 on 2025-10-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0009_remove_city_update_available_city_required_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_confident',
            field=models.BooleanField(default=False),
        ),
    ]
