# Generated by Django 5.2.1 on 2025-12-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_ad_is_confident'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
