# Generated by Django 5.2.1 on 2025-12-17 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_ad_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='ads.ad')),
            ],
            options={
                'verbose_name': 'Жалоба на объявление',
                'verbose_name_plural': 'Жалобы на объявления',
                'ordering': ['-created_at'],
            },
        ),
    ]
