# Generated by Django 4.2.3 on 2025-06-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='city_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('playmarket_link', models.URLField(blank=True, null=True)),
                ('appstore_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
