# Generated by Django 4.2.3 on 2025-11-19 07:13

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_businesscard_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='theme_color',
            field=colorfield.fields.ColorField(blank=True, default='#000000', image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='gradient_end',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='gradient_start',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='businesscategory',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='business/category_icons/'),
        ),
    ]
