# Generated by Django 4.2.3 on 2025-11-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_businesscard_theme_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesscatalogitem',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AlterModelOptions(
            name='businessphoto',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AddField(
            model_name='businesscatalogitem',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businessphoto',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
