# Generated by Django 5.2.1 on 2025-12-05 18:05

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_businesscatalogitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscard',
            name='theme_color',
            field=colorfield.fields.ColorField(blank=True, default='#000000', image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='businesscategory',
            name='gradient_end',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='businesscategory',
            name='gradient_start',
            field=colorfield.fields.ColorField(default='#000000', image_field=None, max_length=25, samples=None),
        ),
    ]
