# Generated by Django 4.2.3 on 2025-11-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='city',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
